server:
  port: 8090

spring:
  boot:
    admin:
      client:
        url: http://localhost:9000
        instance:
          name: it-farm-apiserver   #(어플리케이션 명)
          metadata: # 나의 어플리케이션 (스프링 시큐리티 )로그인 정보
            user.name: admin
            user.password: apwhaleldj1!

  security:
    user:
      name: admin
      password: apwhaleldj1!
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: logs/it.farm.apiserver.log
  level:
    root: info
    com.skan: debug
    org.springframework : info
    web: info