server:
  port: 8000

spring:
  boot:
    admin:
      client:
        url: http://localhost:9000
        #admin monitoring server 의 id
        username: admin
        #admin monitoring server 의 password
        password: admin
        instance:
          name: it-farm-client   #(어플리케이션 명)
          metadata: # 나의 어플리케이션 (스프링 시큐리티 )로그인 정보
            user.name: user1
            user.password: user1
  security:
    user:
      name: user1
      password: user1
#  thymeleaf:
#    mode: LEGACYHTML5
#  mvc:
#    static-path-pattern: /static/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


---
spring:
  profiles: local
  devtools:
    restart:
      enabled: false
  datasource:
    #url: jdbc:h2:mem:naive-it-farm
    url: jdbc:h2:file:~/database/naive-it-farm;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: admin
    password: 1234
  jooq:
    sql-dialect: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database: h2
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
logging:
  file:
    name: logs/it.farm.webapi.log
  level:
    root: info
    com.skan: debug
    org.springframework : info
    org.hibernate.type.descriptor.sql: trace
    web: info

---
spring:
  profiles: test
  devtools:
    restart:
      enabled: false
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/naive-it-farm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: admin
      password: 1234
      maximum-pool-size: 100
  jooq:
    sql-dialect: mysql
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
  data:
    jpa:
      repositories:
        enabled: true
logging:
  file:
    name: logs/it.farm.webapi.log
  level:
    root: info
    com.skan: debug
    org.springframework : info
    org.hibernate.type.descriptor.sql: trace
    web: info


---
spring:
  profiles: dev
  devtools:
    restart:
      enabled: false
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/naive-it-farm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: admin
      password: 1234
      maximum-pool-size: 100
  jooq:
    sql-dialect: mysql
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
  data:
    jpa:
      repositories:
        enabled: true

logging:
  file:
    name: logs/it.farm.webapi.log
  level:
    root: info
    com.skan: debug
    org.springframework : info
    web: info