server:
  port: 8090
spring:
  profiles:
    active: local
  boot:
    admin:
      client:
        url: http://localhost:9000
        instance:
          name: it-farm-apiserver   #(어플리케이션 명)
          metadata: # 나의 어플리케이션 (스프링 시큐리티 )로그인 정보
            user.name: admin
            user.password: admin1!

  security:
    user:
      name: admin
      password: admin1!
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always



---
spring:
  profiles: local
  devtools:
    restart:
      enabled: false
  r2dbc:
    url: r2dbc:h2:file:///c:/Users/mezzomedia/database/naive-it-farm
    username: admin
    password: 1234
    pool:
      max-size: 10
      validation-query: SELECT 1

logging:
  file:
    name: logs/it.farm.apiserver.log
  level:
    root: info
    com.skan: debug
    org.springframework : info
    web: info

---
spring:
  profiles: test
  devtools:
    restart:
      enabled: false

  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/ae_report?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: rootQ1!
    pool:
      max-size: 100
      validation-query: SELECT 1

logging:
  file:
    name: logs/it.farm.apiserver.log
  level:
    root: info
    com.skan: debug
    org.springframework : info
    web: info
---
spring:
  profiles: dev
  devtools:
    restart:
      enabled: false

  r2dbc:
    url: r2dbc:mysql://210.221.235.202:3306/ae_report?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: mezzo2018
    pool:
      max-size: 100
      validation-query: SELECT 1

logging:
  file:
    name: logs/it.farm.apiserver.log
  level:
    root: info
    com.skan: debug
    org.springframework : info
    web: info