server:
  port: 8000

spring:
  boot:
    admin:
      client:
        url: http://localhost:9000
        #username: admin monitoring server 의 id
        #password: admin monitoring server 의 password
        instance:
          name: it-farm-client   #(어플리케이션 명)
          metadata: # 나의 어플리케이션 (스프링 시큐리티 )로그인 정보
            user.name: admin
            user.password: 1
  security:
    user:
      name: admin
      password: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


logging:
  file:
    name: logs/it.farm.client.log
  level:
    root: info
    com.skan: debug
    org.springframework : info
    web: info


