server:
  port: 8000

spring:
  profiles:
    active: local
  boot:
    admin:
      client:
        url: http://localhost:9000
        #username: admin monitoring server 의 id
        #password: admin monitoring server 의 password
        instance:
          name: it-farm-client   #(어플리케이션 명)
          metadata: # 나의 어플리케이션 (스프링 시큐리티 )로그인 정보
            user.name: admin
            user.password: 1
  security:
    user:
      name: admin
      password: 1
#  thymeleaf:
#    mode: LEGACYHTML5
#  mvc:
#    static-path-pattern: /static/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


---
spring:
  profiles: local
  devtools:
    restart:
      enabled: false
  datasource:
    #jdbc-url: jdbc:h2:mem:naive-it-farm
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/database/naive-it-farm;AUTO_SERVER=TRUE
    username: admin
    password: 1234
  jooq:
    sql-dialect: h2
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  file:
    name: logs/it.farm.apiserver.local.log
  level:
    root: info
    com.skan: debug
    org.springframework : info
    web: info

---
spring:
  profiles: test
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ae_report?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: mezzo2018
  jooq:
    sql-dialect: mysql
logging:
  file:
    name: logs/it.farm.apiserver.test.log
  level:
    root: info
    com.skan: debug
    org.springframework : info
    web: info
